baseURL = 'https://scaportugal.coffee/'
languageCode = 'pt-PT'
title = 'SCA Portugal'

[markup.goldmark.renderer]
unsafe= true

[menu]
[[menu.main]]
pageRef = '/'
name = 'Home'
url = '/'
weight = 10
[[menu.main]]
name = '2024 Brewers Cup Leaderboard'
url = '/competitions/brewers-cup/2024/leaderboard'
weight = 20
[[menu.main]]
name = '2024 Cup Tasters Leaderboard'
url = '/competitions/cup-tasters/2024/leaderboard'
weight = 30

